### ISSUE TITLE
Wordmove database push URL rewriting

### ISSUE THREAD

**Issue by good-idea** [yeswework/fabrica-dev-kit#11]
I've configured my Movefile to push everything onto my production site. But, it's appending the port (32768) to all of my URLs. Am I missing a step? How are others handling this, with Movefile or otherwise? I have a clunky method where I'm exporting the database using a plugin, importing, and using another plugin to rewrite the permalinks.. Any simple solutions out there?

**Comment by tiojoca** [comment]
Do you mean that the `localhost` port number is not being removed when you use Wordmove to push the database from development to production? Although we don't necessarily recommend parity between local and production databases, this behaviour seems odd. Could you paste your `dev/Movefile.erb`, or email it to info@fabri.ca, omitting any sensitive information?

**Comment by fewerflatlands** [comment]
Hi @sqbiz, can you let us know if you've now resolved your issue?

**Comment by sqbiz** [comment]
Sorry, i missed the notification from. @tiojoca's message

```
# Wordmove configuration
# for more info see https://github.com/welaika/wordmove/wiki/Movefile-configurations-explained

# Development site settings - do not modify
local:
  vhost: "localhost:<%%= ENV['WEB_PORT'] %>"
  wordpress_path: '<%%= File.expand_path "#{Dir.pwd}/../www/" %>'

  database:
    name: "wordpress"
    user: "root"
    password: "wordpress"
    host: "127.0.0.1"
    port: "32773"

# Production site settings - uncomment and specify for your staging/production environments as required
production:
   vhost: "http://project.myurl.com" # production URL - only needed if you plan to pull/push the database
   wordpress_path: "/var/www/html" # remote path to WordPress (relative to FTP or SSH login)

   database: # remote database credentials - only needed if you plan to pull/push the database
     name: "wordpress"
     user: "wordpress"
     password: "[secret]"
     host: "localhost"
     port: "3308" # optional (for exotic configs)

   exclude:
     - ".git/"
     - ".gitignore"
     - ".sass-cache/"
     - "bin/"
     - "tmp/*"
     - "Gemfile*"
     - "Movefile"
     - "wp-config.php"
     - "wp-content/*.sql"

#   ftp: # be sure to specify the wordpress_path parameter above too
#     user: "user"
#     password: "password"
#     host: "host"
#     passive: true
#     scheme: "ftps" # optional (default "ftp")
#     port: "3308" # optional (for exotic configs)

   ssh: # be sure to specify the wordpress_path parameter above too
     host: "101.102.103.104"
     user: "username"
#     password: "password" # password is optional, will use public keys if available.
     port: 22 # Port is optional
     rsync_options: "--verbose" # Additional rsync options, optional
#     gateway: # Gateway is optional
#       host: "host"
#       user: "user"
#       password: "password" # password is optional, will use public keys if available.
```

At this point, I'm using wordmove to handle the theme & any uploads I might need to push. For the database, I'm manually exporting it using a plugin, importing that into the database on the server using the command line, then using that same plugin to rewrite any existing URLs.

Note that some of these URLs are in entries from the WP-Types plugin.
